baseURL: 'https://ayasuda.com'
title: "ayasuda.com"
pagination:
  pageSize: 10
theme: PaperMod

languageCode: ja-jp
hasCJKLanguage: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-CP4DJY2LGV

minify:
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS


params:
  title: "ayasuda.com"
  description: "ayasuda の個人的なホームページ"
  keyword: [Blog, ayasuda]
  author: ayasuda
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  profileMode:
    enabled: true
    subtitle: "ayasuda の個人的なページ"
    imageUrl: img/profile.jpg
    buttons:
      - name: Posts
        url: pages
      - name: Tags
        url: tags

menu:
  main:
    - identifier: posts
      name: Posts
      url: pages/
      weight: 10
