[build]
  publish = "public"
  command = "hugo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.147.8"
  GIT_SUBMODULE_STRATEGY = "recursive"

[context.production.environment]
  HUGO_VERSION = "0.147.8"
  GIT_SUBMODULE_STRATEGY = "recursive"
